otc_web:
    resource: "@OtcWebBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

otc_user:
    resource: "@OtcUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

otc_core:
    resource: "@OtcCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}/
