parameters:
    otc_core.datetime_format_extension.class: Otc\CoreBundle\Twig\DateFormatExtension
services:

    otc_core.datetime_format_extension:
        class: %otc_core.datetime_format_extension.class%
        arguments: [@service_container]
        public: false
        tags:
            - { name: twig.extension }
