services:
#    otc_core.example:
#        class: Otc\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    otc_core.tanslation.locales:
        class: stdClass
        arguments: [@translator]
